---
- name: Get latest release version from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/mikefarah/yq/releases/latest
    return_content: yes
  register: _yq_latest

- name: Make directory for yq
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/yq/{{ _yq_latest.json.tag_name }}'
    state: directory

- name: Get yq
  ansible.builtin.unarchive:
    src: https://github.com/mikefarah/yq/releases/download/{{ _yq_latest.json.tag_name }}/yq_linux_amd64.tar.gz
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/yq/{{ _yq_latest.json.tag_name }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/yq/{{ _yq_latest.json.tag_name }}/yq'

- name: Put yq symlink in local bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/yq'
    state: link
    src: '{{ ansible_env.HOME }}/.local/lib/yq/{{ _yq_latest.json.tag_name }}/yq_linux_amd64'
