- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/danielgtaylor/restish/releases/latest'
    return_content: yes
  register: _restish_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _restish_version: '{{ _restish_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/restish/restish-{{ _restish_version }}'
    state: directory

- name: 'download {{ _restish_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/danielgtaylor/restish/releases/download/{{ _restish_version }}/restish-{{ _restish_version[1:] }}-linux-amd64.tar.gz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/restish/restish-{{ _restish_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/restish/restish-{{ _restish_version }}/restish'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/restish'
    src: '{{ ansible_env.HOME }}/.local/lib/restish/restish-{{ _restish_version }}/restish'
    state: link

- name: directory for completions
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions'
    state: directory
    mode: 0755

- name: add completions script
  ansible.builtin.shell:
    cmd: >
      {{ ansible_env.HOME }}/.local/bin/restish completion bash >
      {{ ansible_env.HOME }}/.local/share/bash-completion/completions/restish
    creates: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions/restish'
