- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/duckdb/duckdb/releases/latest'
    return_content: yes
  register: _duckdb_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _duckdb_version: '{{ _duckdb_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/duckdb/duckdb-{{ _duckdb_version }}'
    state: directory

- name: 'download {{ _duckdb_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/duckdb/duckdb/releases/download/{{ _duckdb_version }}/duckdb_cli-linux-amd64.zip'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/duckdb/duckdb-{{ _duckdb_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/duckdb/duckdb-{{ _duckdb_version }}/duckdb'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/duckdb'
    src: '{{ ansible_env.HOME }}/.local/lib/duckdb/duckdb-{{ _duckdb_version }}/duckdb'
    state: link
