---
- name: Dependencies
  ansible.builtin.apt:
    name:
      - zip
      - unzip
      - curl
  become: true

- name: Install # noqa command-instead-of-module
  ansible.builtin.shell:
    cmd: curl -s 'https://get.sdkman.io?rcupdate=false' | bash
    creates: "{{ sdkman_dir }}"
  environment:
    SDKMAN_DIR: "{{ sdkman_dir }}"

- name: Update
  ansible.builtin.shell:
    cmd: "source {{ sdkman_dir }}/bin/sdkman-init.sh && sdk selfupdate"
    executable: /bin/bash
  register: _sdkman_selfupdate
  changed_when: _sdkman_selfupdate.stdout != 'No update available at this time.'

- name: Configure .*rc files
  ansible.builtin.include_tasks: shell_config.yml

- name: Configure sdkman
  ansible.builtin.copy:
    dest: "/home/teamcity/.sdkman/etc/config"
    content: |
      sdkman_auto_answer=false
      sdkman_auto_complete=true
      sdkman_auto_env=false
      sdkman_beta_channel=false
      sdkman_checksum_enable=true
      sdkman_colour_enable=true
      sdkman_curl_connect_timeout=20
      sdkman_curl_max_time=100
      sdkman_debug_mode=true
      sdkman_insecure_ssl=false
      sdkman_native_enable=true
      sdkman_selfupdate_feature=true
