- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/casey/just/releases/latest'
    return_content: yes
  register: _just_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _just_version: '{{ _just_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/just/just-{{ _just_version }}'
    state: directory

- name: 'download {{ _just_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/casey/just/releases/download/{{ _just_version }}/just-{{ _just_version }}-x86_64-unknown-linux-musl.tar.gz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/just/just-{{ _just_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/just/just-{{ _just_version }}/just'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/just'
    src: '{{ ansible_env.HOME }}/.local/lib/just/just-{{ _just_version }}/just'
    state: link

- name: directory for completions
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions'
    state: directory
    mode: 0755

- name: add completions script
  ansible.builtin.shell:
    cmd: >
      {{ ansible_env.HOME }}/.local/bin/just --completions bash >
      {{ ansible_env.HOME }}/.local/share/bash-completion/completions/just
    creates: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions/just'
