#!/usr/bin/env bash
# {{ ansible_managed }}
# Hook checks if there is a pre-commit config file in the repo and if there is, verifies that the pre-commit hook is installed.
set -u -o pipefail

RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PRE_COMMIT_CONFIG_FILE="$(git rev-parse --show-toplevel)/.pre-commit-config.yaml"
LOCAL_PRE_COMMIT_HOOK="$(git rev-parse --git-dir)/.git/hooks/pre-commit"

if [ -f "$PRE_COMMIT_CONFIG_FILE" ]; then
    if [ ! -x "$LOCAL_PRE_COMMIT_HOOK" ]; then
        echo -e "${RED}ERROR${NC}: Local pre-commit hook is not installed. Run 'pre-commit install' to install it."
        echo "       Found pre-commit config file at ${PRE_COMMIT_CONFIG_FILE}".
        exit 1
    fi
fi
