- name: get latest steampipe version
  uri:
    url: https://api.github.com/repos/turbot/steampipe/releases/latest
    return_content: yes
  register: _steampipe_latest

- name: make directory for steampipe
  file:
    path: '{{ ansible_env.HOME }}/.local/lib/steampipe/{{ _steampipe_latest.json.name }}'
    state: directory

- name: get steampipe
  unarchive:
    src: https://github.com/turbot/steampipe/releases/download/{{ _steampipe_latest.json.name }}/steampipe_linux_amd64.tar.gz
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/steampipe/{{ _steampipe_latest.json.name }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/steampipe/{{ _steampipe_latest.json.name }}/steampipe'

- name: put steampipe symlink in local bin
  file:
    path: '{{ ansible_env.HOME }}/.local/bin/steampipe'
    state: link
    src: '{{ ansible_env.HOME }}/.local/lib/steampipe/{{ _steampipe_latest.json.name }}/steampipe'

- name: install oci plugin
  command:
    cmd: '{{ ansible_env.HOME }}/.local/bin/steampipe plugin install oci'
    creates: '{{ ansible_env.HOME }}/.steampipe/plugins/hub.steampipe.io/plugins/turbot/oci@latest/steampipe-plugin-oci.plugin'
