- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/ariga/atlas/releases/latest'
    return_content: yes
  register: _atlas_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _atlas_version: '{{ _atlas_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/atlas'
    state: directory

- name: 'download {{ _atlas_version }}'
  ansible.builtin.get_url:
    url: 'https://release.ariga.io/atlas/atlas-linux-amd64-{{ _atlas_version }}'
    dest: '{{ ansible_env.HOME }}/.local/lib/atlas/atlas-linux-amd64-{{ _atlas_version }}'
    mode: 0755

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/atlas'
    src: '{{ ansible_env.HOME }}/.local/lib/atlas/atlas-linux-amd64-{{ _atlas_version }}'
    state: link

- name: directory for completions
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions'
    state: directory
    mode: 0755

- name: add completions script
  ansible.builtin.shell:
    cmd: >
      {{ ansible_env.HOME }}/.local/bin/atlas completion bash >
      {{ ansible_env.HOME }}/.local/share/bash-completion/completions/atlas
    creates: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions/atlas'
