---
- name: Install Kotlin packages
  ansible.builtin.shell: >
    source {{ kotlin_sdkman_dir }}/bin/sdkman-init.sh &&
    sdk install kotlin {{ item }}
  args:
    executable: /bin/bash
  register: sdk_install
  loop: '{{ kotlin_sdkman_install_versions }}'
  changed_when: |
    'is already installed.' not in sdk_install.stdout
  failed_when: |
    sdk_install.rc != 0 and 'is already installed.' not in sdk_install.stdout

- name: Uninstall SDK candidates/versions
  ansible.builtin.shell: >
    source {{ kotlin_sdkman_dir }}/bin/sdkman-init.sh &&
    sdk uninstall kotlin {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ kotlin_sdkman_uninstall_versions }}"
  register: sdk_uninstall
  changed_when: not 'is not installed.' in sdk_uninstall.stdout

- name: Get SDK defaults
  ansible.builtin.shell: source {{ kotlin_sdkman_dir }}/bin/sdkman-init.sh && sdk current kotlin
  args:
    executable: /bin/bash
  register: get_sdk_defaults
  changed_when: false

- name: Set SDK defaults
  ansible.builtin.shell: source {{ kotlin_sdkman_dir }}/bin/sdkman-init.sh && sdk default kotlin {{ kotlin_sdkman_default_version | first }}
  args:
    executable: /bin/bash
  changed_when: not (kotlin_sdkman_default_version | first) in get_sdk_defaults.stdout
