---
namespace: elhub
name: wsl
version: 0.2.2
readme: README.md
authors:
  - "@elhub/devxp"
description: >
  WSL Ansible Collection that facilitates the installation and configuration
  of the varied Linux(WSL) tools that are used at Elhub.
license:
  - MIT
tags: ['infrastructure']
dependencies: {}
repository: https://github.com/elhub/devxp-ansible-collection-wsl
documentation: https://github.com/elhub/devxp-ansible-collection-wsl/blob/main/README.md
issues: https://jira.elhub.cloud/projects/TDX/issues
