---
- name: install dependencies
  ansible.builtin.apt:
    name:
      - libssl-dev
      - libffi-dev
      - build-essential
      - python3-dev
      - python3-venv
  become: yes

- name: install oci cli in venv
  ansible.builtin.pip:
    name: '{{ item }}'
    state: latest
    virtualenv: '{{ ansible_env.HOME }}/.local/lib/oci'
    virtualenv_command: /usr/bin/python3 -m venv
  loop: # doing it as a loop since we want pip to upgrade first, then install the other stuff
    - pip
    - oci-cli

- name: symlink binary
  ansible.builtin.file:
    dest: '{{ ansible_env.HOME }}/.local/bin/oci'
    src: '{{ ansible_env.HOME }}/.local/lib/oci/bin/oci'
    state: link

- name: oci sdk
  ansible.builtin.pip:
    name: oci
    state: latest
    extra_args: --user
