---
- name: add git branch to prompt
  blockinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    marker: '# {mark} Ansible - add git branch to prompt'
    block: |
      # add git branch to prompt
      #shameless nick and modification from https://stackoverflow.com/questions/4133904/ps1-line-with-git-current-branch-and-colors
      parse_git_branch() {
          git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }

      export PS1='\[\e[1;32m\]\u\[\e[0;39m\]@\[\e[1;36m\]\h\[\e[0;39m\]:\[\e[1;33m\]\w\[\e[0;39m\]\[\e[1;35m\]$(parse_git_branch " (%s)")\[\e[0;39m\] \[\e[0;39m\]\$'
  tags:
    - bash_decorations
