---
- name: Converge
  hosts: all
  tasks:
    - name: "Install base"
      ansible.builtin.include_role:
        name: base
    - name: "Install git_utils"
      ansible.builtin.include_role:
        name: git_utils
