---
linters_default_linters:
  - checkstyle
  - detekt

linters_install_path: "{{ ansible_env.HOME }}/.local"

linters_lint_config_path: "{{ linters_install_path }}/lint-config"

# Version of checkstyle to install
linters_checkstyle_version: 9.0

# Version of detekt to install
linters_detekt_version: 1.18.1

# Version of yamllint
linters_yamllint_version: 1.20.0
