---
- name: Clear GitHub CLI GPG keyring
  file:
    path: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    state: absent
  become: true
- name: Clear GitHub CLI source list
  file:
    path: /etc/apt/sources.list.d/github-cli.list
    state: absent
  become: true

- name: Install GitHub CLI
  ansible.builtin.shell: >
    (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
    && sudo mkdir -p -m 755 /etc/apt/keyrings \
    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo apt update \
    && sudo apt install gh -y
  register: apt_install_gh_output
  changed_when: |
   '1 newly installed' in apt_install_gh_output.stdout
