- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/typst/typst/releases/latest'
    return_content: yes
  register: _typst_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _typst_version: '{{ _typst_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/typst/typst-{{ _typst_version }}'
    state: directory

- name: 'download {{ _typst_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/typst/typst/releases/download/{{ _typst_version }}/typst-x86_64-unknown-linux-musl.tar.xz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/typst/typst-{{ _typst_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/typst/typst-{{ _typst_version }}/typst'
    extra_opts: ['--strip-components=1']

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/typst'
    src: '{{ ansible_env.HOME }}/.local/lib/typst/typst-{{ _typst_version }}/typst'
    state: link
