---
# Default user for docker. Defaults to 'ansible_user_id'
# Can be overidden with the following variable
# docker_user: jane.doe

docker_http_proxy_param: ''
docker_https_proxy_param: ''

# Install docker ansible dependencies with pip
# Set this to false, e.g. if ansible is installed via pipx
docker_ansible_dependencies_pip: true
