---
- name: Converge
  hosts: all
  tasks:
    - name: "Install base"
      ansible.builtin.include_role:
        name: base
    - name: "Install java"
      ansible.builtin.include_role:
        name: java
    - name: "Install adr"
      ansible.builtin.include_role:
        name: adr
