- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/protocolbuffers/protobuf/releases/latest'
    return_content: yes
  register: _protoc_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _protoc_version: '{{ _protoc_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/protoc/protoc-{{ _protoc_version }}'
    state: directory

- name: 'download {{ _protoc_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/protocolbuffers/protobuf/releases/download/{{ _protoc_version }}/protoc-{{ _protoc_version[1:] }}-linux-x86_64.zip'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/protoc/protoc-{{ _protoc_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/protoc/protoc-{{ _protoc_version }}/bin/protoc'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/protoc'
    src: '{{ ansible_env.HOME }}/.local/lib/protoc/protoc-{{ _protoc_version }}/bin/protoc'
    state: link
