---
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    volumes:
      - /var/lib/docker
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  create_sequence: []
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - verify
    - destroy
