---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test checkstyle
      ansible.builtin.shell: "source ~/.sdkman/bin/sdkman-init.sh && ~/.local/bin/checkstyle --version"
      args:
        executable: /bin/bash
      changed_when: false

    - name: Test detekt
      ansible.builtin.shell: "source ~/.sdkman/bin/sdkman-init.sh && ~/.local/bin/detekt --version"
      args:
        executable: /bin/bash
      changed_when: false
