---
- name: Ensure install path exists
  ansible.builtin.file:
    path: "{{ linters_lint_config_path }}"
    state: directory
    mode: 0755

- name: Include checkstyle
  ansible.builtin.include_tasks: checkstyle.yml
  when: '"checkstyle" in linters_default_linters'

- name: Include detekt
  ansible.builtin.include_tasks: detekt.yml
  when: '"detekt" in linters_default_linters'
