- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/go-task/task/releases/latest'
    return_content: yes
  register: _task_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _task_version: '{{ _task_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/task/task-{{ _task_version }}'
    state: directory

- name: 'download {{ _task_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/go-task/task/releases/download/{{ _task_version }}/task_linux_amd64.tar.gz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/task/task-{{ _task_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/task/task-{{ _task_version }}/task'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/task'
    src: '{{ ansible_env.HOME }}/.local/lib/task/task-{{ _task_version }}/task'
    state: link

- name: directory for completions
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions'
    state: directory
    mode: 0755

- name: symlink completions
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/share/bash-completion/completions/task'
    src: '{{ ansible_env.HOME }}/.local/lib/task/task-{{ _task_version }}/completion/bash/task.bash'
    state: link
