---
- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Create a temporary file for the GPG key 
  ansible.builin.tempfile:
    state: file
    suffix: '.gpg'
  register: temp_mise_gpg_key

- name: Download the repository's GPG key
  ansible.builtin.get_url:
    url: https://mise.jdx.dev/gpg-key.pub
    dest: "{{ temp_mise_gpg_key.path }}"
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Deamor the GPG key
  ansible.builtin.command:
    cmd: gpg --no-tty --batch --dearmor --output /etc/apt/keyrings/mise-archive-keyring.gpg "{{ temp_mise_gpg_key.path }}"
  become: true

- name: Clean up the temporary GPG file
  ansible.builtin.file:
    path: "{{ temp_mise_gpg_key.path }}"
    state: absent
  become: true

- name: Add the mise repository to the apt sources list 
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main"
    filename: "mise"
    state: present
  become: true

- name: Update the apt package list
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install mise-en-place
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: yes
  become: true

- name: Add mise-en-place to PATH
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.shrc.d/60-mise.sh"
    mode: '0644'
    content: |
      # Managed by Ansible - elhub.wsl.mise
      shell="$(readlink /proc/$$/exe | sed "s/.*\///")"
      eval "$(mise activate ${shell})"
