---
- name: Install mise-en-place  
  ansible.builtin.shell: curl https://mise.run | sh
  args:
    creates: "{{ mise_path }}"

- name: Add mise-en-place to PATH
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.shrc.d/60-mise.sh"
    mode: '0644'
    content: |
      # Managed by Ansible - elhub.wsl.mise
      script_shell="$(readlink /proc/$$/exe | sed "s/.*\///")"
      if [[ "${script_shell}" == "bash" ]]
      then
          eval "$(mise activate bash)"
      elif [[ "${script_shell}" == "zsh" ]]
      then
          eval "$(mise activate zsh)"
      fi
