---
- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Fetch the GPG key content
  ansible.builtin.uri:
    url: https://mise.jdx.dev/gpg-key.pub
    return_content: true
  register: gpg_key_content

- name: Save and deamor the GPG key
  ansible.builtin.shell: |
    echo "{{ gpg_key_content.content }}" | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg > /dev/null
  become: true

- name: Add the mise repository to the apt sources list 
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main"
    filename: "mise"
    state: present
  become: true

- name: Update the apt package list
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install mise-en-place
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: yes
  become: true

- name: Add mise-en-place to PATH
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.shrc.d/60-mise.sh"
    mode: '0644'
    content: |
      # Managed by Ansible - elhub.wsl.mise
      shell="$(readlink /proc/$$/exe | sed "s/.*\///")"
      eval "$(mise activate ${shell})"
