---
- name: Install mise-en-place  
  ansible.builtin.shell: curl https://mise.run | sh
  args:
    creates: "{{ mise_path }}"

- name: Add mise-en-place to PATH
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.shrc.d/60-mise.sh"
    mode: '0644'
    content: |
      # Managed by Ansible - elhub.wsl.mise
      export PATH="$HOME/.local/share/mise/shims:$PATH"
      eval "$(mise activate bash)"
      eval "$(mise activate zsh)"

