---
- name: Add ppa:jdxcode/mise repository
  ansible.builtin.deb822_repository:
    state: present
    name: "jdxcode-mise-{{ ansible_facts['distribution_release'] }}"
    types: deb
    uris: https://ppa.launchpadcontent.net/jdxcode/mise/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    # Search string found on https://launchpad.net/~jdxcode/+archive/ubuntu/mise
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x38A097C0CCE691795E4B15BE23997D3EEE1EDC52
  become: true

- name: Install mise-en-place
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: true
  become: true

- name: Add mise-en-place to bash PATH
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.shrc.d/60-mise.bash"
    mode: '0644'
    content: |
      # Managed by Ansible - elhub.wsl.mise
      eval "$(mise activate bash)"

- name: Add mise-en-place to zsh PATH
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.shrc.d/60-mise.zsh"
    mode: '0644'
    content: |
      # Managed by Ansible - elhub.wsl.mise
      eval "$(mise activate zsh)"
