- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/k1LoW/tbls/releases/latest'
    return_content: yes
  register: _tbls_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _tbls_version: '{{ _tbls_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/tbls/tbls-{{ _tbls_version }}'
    state: directory

- name: 'download {{ _tbls_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/k1LoW/tbls/releases/download/{{ _tbls_version }}/tbls_{{ _tbls_version }}_linux_amd64.tar.gz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/tbls/tbls-{{ _tbls_version }}'
    creates: '{{ ansible_env.HOME }}/.local/lib/tbls/tbls-{{ _tbls_version }}/tbls'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/tbls'
    src: '{{ ansible_env.HOME }}/.local/lib/tbls/tbls-{{ _tbls_version }}/tbls'
    state: link
