#!/usr/bin/env bash
set -u -o pipefail

allowed_msg=(
    "feat: SOME-123" \
    "fix: SOME-123 asdasd" \
)

disallowed_msg=(
    "revert: some msg" \
    "some random message" \
    "feat: some msg that is way too long and should not be allowed adasd aasdadasdasdsad" \
)

tmp_file=$(mktemp)

for msg in "${allowed_msg[@]}"; do
    echo "$msg" > $tmp_file
    out=$(./jira $tmp_file 2>&1)
    if [ ${#out} -gt 0 ]; then
        echo "Test failed for: $msg"
        exit 1
    fi
done


for msg in "${disallowed_msg[@]}"; do
    echo "$msg" > $tmp_file
    out=$(./jira $tmp_file 2>&1)
    if [ ${#out} -eq 0 ]; then
        echo "Test failed for: $msg"
        exit 1
    fi
done

echo "All good!"
