---
- name: Install Java packages
  ansible.builtin.shell: |
    #!/bin/bash
    source {{ java_sdkman_dir }}/bin/sdkman-init.sh
    set -x
    echo "HTTP_PROXY: $HTTP_PROXY"
    echo "HTTPS_PROXY: $HTTPS_PROXY"
    echo "NO_PROXY: $NO_PROXY"
    echo "http_proxy: $http_proxy"
    echo "https_proxy: $https_proxy"
    echo "no_proxy: $no_proxy"
    cat /home/teamcity/.curlrc
    sdk install java {{ item }}
    set +x
  args:
    executable: /bin/bash
  loop: "{{ java_sdkman_install_versions }}"
  register: sdk_install
  changed_when: |
    'is already installed.' not in sdk_install.stdout
  failed_when: |
    sdk_install.rc != 0 and 'is already installed.' not in sdk_install.stdout

- name: Uninstall SDK candidates/versions
  ansible.builtin.shell: >
    source {{ java_sdkman_dir }}/bin/sdkman-init.sh &&
    sdk uninstall java {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ java_sdkman_uninstall_versions }}"
  register: sdk_uninstall
  changed_when: not 'is not installed.' in sdk_uninstall.stdout

- name: Get SDK defaults
  ansible.builtin.shell: source {{ java_sdkman_dir }}/bin/sdkman-init.sh && sdk current java
  args:
    executable: /bin/bash
  register: get_sdk_defaults
  changed_when: false

- name: Set SDK defaults
  ansible.builtin.shell: source {{ java_sdkman_dir }}/bin/sdkman-init.sh && sdk default java {{ java_sdkman_default_version | first }}
  args:
    executable: /bin/bash
  changed_when: not (java_sdkman_default_version | first) in get_sdk_defaults.stdout
