---
- name: Converge
  hosts: all
  tasks:
    - name: "Install base"
      ansible.builtin.include_role:
        name: base
    - name: "Install molecule"
      ansible.builtin.include_role:
        name: molecule
