- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/streamdal/plumber/releases/latest'
    return_content: yes
  register: _plumber_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _plumber_version: '{{ _plumber_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/plumber/plumber-{{ _plumber_version }}'
    state: directory

- name: 'download {{ _plumber_version }}'
  ansible.builtin.get_url:
    url: 'https://github.com/streamdal/plumber/releases/download/{{ _plumber_version }}/plumber-linux'
    dest: '{{ ansible_env.HOME }}/.local/lib/plumber/plumber-{{ _plumber_version }}/plumber-linux'
    mode: 0750

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/plumber'
    src: '{{ ansible_env.HOME }}/.local/lib/plumber/plumber-{{ _plumber_version }}/plumber-linux'
    state: link
