---
- name: Ensure ansible
  ansible.builtin.pip:
    name: ansible
    extra_args: --user
    state: present
    version: "{{ ansible_install_version }}"
  environment:
    DISPLAY: ''  # Fix to resolve extremely slow installs on WSL2 (see https://github.com/microsoft/WSL/issues/6643)

- name: Ensure ansible pip dependencies
  ansible.builtin.pip:
    name:
      - jmespath
      - dnspython
      - lxml
    extra_args: --user
    state: present
  environment:
    DISPLAY: ''  # Fix to resolve extremely slow installs on WSL2 (see https://github.com/microsoft/WSL/issues/6643)
