---
- name: Ensure ansible
  pip:
    name: ansible
    extra_args: --user
    state: latest
  environment:
    DISPLAY: ''  # Fix to resolve extremely slow installs on WSL2 (see https://github.com/microsoft/WSL/issues/6643)

- name: Ensure ansible pip dependencies
  pip:
    name:
      - jmespath
      - dnspython
      - lxml
    extra_args: --user
    state: latest
  environment:
    DISPLAY: ''  # Fix to resolve extremely slow installs on WSL2 (see https://github.com/microsoft/WSL/issues/6643)
