---
galaxy_info:
  role_name: node
  namespace: elhub
  author: elhub/devxp
  description: See README
  company: Elhub
  license: MIT
  min_ansible_version: "2.2"
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags: []
