---
- name: Ensure nvm is installed # noqa command-instead-of-module
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ node_nvm_version }}/install.sh | bash
  args:
    creates: "{{ node_nvm_install_path }}/nvm.sh"

- name: Install node
  ansible.builtin.shell: |
    . {{ node_nvm_install_path }}/nvm.sh
    nvm install {{ node_node_version }}
  args:
    executable: /bin/bash
  register: node_version_response
  changed_when: "'already installed' not in node_version_response.stderr"
