---
- name: install fn cli
  get_url:
    url:
    url: https://github.com/fnproject/cli/releases/download/0.6.24/fn_linux
    dest: "{{ ansible_env.HOME }}/.local/bin/fn"
    checksum: md5:3a0432b9a2478cd630efcf8cbe5c5c50
    mode: 0751
  tags:
    - fn
    - optionals