---
- name: ensure cpanminus for installing perl dependencies
  ansible.builtin.apt:
    name: cpanminus
    state: present
  become: true

- name: default configuration for cpan local::lib
  ansible.builtin.shell:
    cmd: /usr/bin/yes '' | /usr/bin/perl -MCPAN -e 'mkmyconfig'
    creates: '{{ ansible_env.HOME }}/.cpan/CPAN/MyConfig.pm'

- name: install perl dependencies for building DBD::Oracle
  community.general.cpanm:
    name: '{{ item }}'
  loop:
    - 'DBI'
    - 'Test::NoWarnings'

- name: symlink some libs so that we are able to bild DBD::Oracle
  ansible.builtin.file:
    state: link
    src: '{{ item }}.19.1'
    dest: '{{ ora2pg_oracle_home }}/{{ item }}'
  loop:
    - libclntsh.so
    - libclntshcore.so

- name: perl - DBD::Oracle
  community.general.cpanm:
    name: 'DBD::Oracle'
  environment:
    ORACLE_HOME: '{{ ora2pg_oracle_home }}'
    LD_LIBRARY_PATH: '{{ ora2pg_oracle_home }}'

- name: perl - Other modules
  community.general.cpanm:
    name: '{{ item }}'
  loop:
    - 'Time::HiRes'
    - 'Compress::Zlib'
    - 'Term::ReadKey'

- name: make .local directory for ora2pg
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/ora2pg'
    state: directory

- name: get ora2pg
  ansible.builtin.unarchive:
    src: https://github.com/darold/ora2pg/archive/refs/tags/v23.2.tar.gz
    dest: '{{ ansible_env.HOME }}/.local/lib/ora2pg'
    remote_src: true
    creates: '{{ ansible_env.HOME }}/.local/lib/ora2pg/ora2pg-23.2/Makefile.PL'

- name: prepare ora2pg
  ansible.builtin.shell:
    cmd: '{{ item.cmd }}'
    chdir: '{{ ansible_env.HOME }}/.local/lib/ora2pg/ora2pg-23.2'
    creates: '{{ ansible_env.HOME }}/.local/lib/ora2pg/{{ item.creates }}'
  loop:
    - cmd: >
        /usr/bin/perl Makefile.PL
        CONFDIR={{ ansible_env.HOME }}/.ora2pg
        DOCDIR={{ ansible_env.HOME }}/.local/lib/ora2pg/doc
        ORACLE_HOME={{ ora2pg_oracle_home }}
      creates: 'ora2pg-23.2/Makefile'
    - cmd: '/usr/bin/make'
      creates: 'ora2pg-23.2/blib/script/ora2pg'

- name: install ora2pg
  ansible.builtin.shell:
    cmd: /usr/bin/make install
    chdir: '{{ ansible_env.HOME }}/.local/lib/ora2pg/ora2pg-23.2'
    creates: '{{ ansible_env.HOME }}/perl5/bin/ora2pg'
  become: true

# Please fix the below task
- name: patch ora2pg
  ansible.builtin.lineinfile:
    # I was getting Undefined subroutine &Ora2Pg::ReadMode
    # even tho Term::ReadKey is installed.
    # This is just a dirty hack to fix it.
    # https://github.com/darold/ora2pg/issues/1260
    path: '{{ ansible_env.HOME }}/perl5/lib/perl5/Ora2Pg.pm'
    line: 'use Term::ReadKey;'
    insertafter: '^use Encode'
