- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/terrastruct/d2/releases/latest'
    return_content: yes
  register: _d2_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _d2_version: '{{ _d2_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/d2'
    state: directory

- name: 'download {{ _d2_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/terrastruct/d2/releases/download/{{ _d2_version }}/d2-{{ _d2_version }}-linux-amd64.tar.gz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/d2'
    creates: '{{ ansible_env.HOME }}/.local/lib/d2/d2-{{ _d2_version }}/bin/d2'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/d2'
    src: '{{ ansible_env.HOME }}/.local/lib/d2/d2-{{ _d2_version }}/bin/d2'
    state: link
