---
- name: Converge
  hosts: all
  become: false
  tasks:
    - name: "Install base"
      ansible.builtin.include_role:
        name: base
    - name: "Install python"
      ansible.builtin.include_role:
        name: python
