---
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    volumes:
      - /var/lib/docker
    privileged: true
    pre_build_image: true
lint: |
  set -e
  wget https://raw.githubusercontent.com/elhub/devxp-lint-configuration/main/resources/.ansible-lint -O .ansible-lint
  ~/.local/lib/molecule-venv/bin/yamllint .
  ~/.local/lib/molecule-venv/bin/ansible-lint -c .ansible-lint --exclude .ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
