---
- name: Install pre-requisites for installing Docker
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: Get the system architecture of your computer and put it in a variable
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: _docker_system_architecture

- name: Add apt signing key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add apt repository for Docker stable version
  ansible.builtin.apt_repository:
    repo: deb [arch="{{ _docker_system_architecture.stdout }}"] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    state: present
  become: true

- name: Install Docker and its dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  become: true
