---
- name: Install pre-requisites for installing Docker
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    state: present
    name: "docker-{{ ansible_facts['distribution_release'] }}"
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Install Docker and its dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  become: true
