---
- name: Add {{ ansible_env.HOME }}/.local paths
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/{{ item }}"
    mode: 0755
    state: directory
  loop:
    - bin
    - etc
    - lib

- name: Include ssh gnupg-agent
  ansible.builtin.include_tasks: sshagent.yml
- name: Include packages
  ansible.builtin.include_tasks: packages.yml
- name: Include screen directory
  ansible.builtin.include_tasks: screendir.yml
