---
- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  become: true

- name: Ensure default packages
  ansible.builtin.package:
    name: "{{ base_default_packages }}"
    state: present
  become: true
  retries: 3

- name: Ensure configured packages
  ansible.builtin.package:
    name: "{{ base_config_packages }}"
    state: present
  become: true
  retries: 3
