---
# https://superuser.com/questions/1195962/cannot-make-directory-var-run-screen-permission-denied/1284329#1284329
- name: Make local screendir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.screen"
    state: directory
    mode: 0700

- name: Set screendir env var
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: '^export SCREENDIR='
    line: 'export SCREENDIR=$HOME/.screen'
