- name: get latest release version from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/jgm/pandoc/releases/latest'
    return_content: yes
  register: _pandoc_latest

- name: register reusable version var
  ansible.builtin.set_fact:
    _pandoc_version: '{{ _pandoc_latest.json.tag_name }}'

- name: create dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/lib/pandoc'
    state: directory

- name: 'download {{ _pandoc_version }}'
  ansible.builtin.unarchive:
    src: 'https://github.com/jgm/pandoc/releases/download/{{ _pandoc_version }}/pandoc-{{ _pandoc_version }}-linux-amd64.tar.gz'
    remote_src: yes
    dest: '{{ ansible_env.HOME }}/.local/lib/pandoc'
    creates: '{{ ansible_env.HOME }}/.local/lib/pandoc/pandoc-{{ _pandoc_version }}/bin/pandoc'

- name: symlink bin
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin/pandoc'
    src: '{{ ansible_env.HOME }}/.local/lib/pandoc/pandoc-{{ _pandoc_version }}/bin/pandoc'
    state: link
